pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'docker build . -t npm-test'
            }
        }
        stage('Deploy') {
            steps {
                echo 'docker kill $(docker ps -q) || true && docker rm $(docker ps -a -q) || true'
            }
        }
        stage('Publish') {
            steps {
                sh 'docker run -p 8079:8079 -d npm-test'
            }
        }
    }
}